apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  namespace: monitoring
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: us-west-2a
allowVolumeExpansion: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-claim
  namespace: monitoring
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 78Gi
